const phones = [
    {
      id: 1,
      type: "p",
      name: "갤럭시 Z 폴드 7",
      img: "img/p7.avif",
      content: "갤럭시 Z 폴드7, 울트라를 펼치다",
      price: 2296200,
    },
    {
      id: 2,
      type: "p",
      name: "갤럭시 A15",
      img: "img/a15.avif",
      content: "갤럭시 A15, 날개를 펼치다",
      price: 1260000,
    },
    {
      id: 3,
      type: "p",
      name: "갤럭시 A36",
      img: "img/a36.avif",
      content: "갤럭시 A36, 신속하게",
      price: 1455000,
    },
    {
      id: 4,
      type: "p",
      name: "퀀텀 6",
      img: "img/q6.avif",
      content: "삼성 퀀텀 6, 저렴하게 ",
      price: 8600000,
    },
    {
      id: 5,
      type: "p",
      name: "갤럭시 s24",
      img: "img/s24.avif",
      content: "갤럭시 별을 달다",
      price: 14500,
    },
    {
      id: 6,
      type: "p",
      name: "갤럭시 s24 울트라",
      img: "img/s24u.avif",
      content: "갤럭시 s24 울트라, 더 향상된 성능으로",
      price: 17000,
    },
    {
      id: 7,
      type: "p",
      name: "갤럭시 s25",
      img: "img/s25.avif",
      content: "갤럭시 25시간 돌아간다.",
      price: 20000,
    },
    {
      id: 8,
      type: "p",
      name: "갤럭시 s25 울트라",
      img: "img/s25u.avif",
      content: "갤럭시 25 울트라, 끝에 다다르는",
      price: 25000,
    },
    {
      id: 9,
      type: "p",
      name: "갤럭시 z 폴드 5",
      img: "img/z5.avif",
      content: "접는 것 마저 완벽하게",
      price: 18500,
    },
  ];
  
